### ISSUE TITLE
TypeError: validateFEN is not a function

### ISSUE THREAD

**Issue by corysimmons** [jayasurian123/fen-validator#13]
The package on npm says the function isn't exported. Copying your README here:

![image](https://user-images.githubusercontent.com/224636/102672901-29453780-4160-11eb-841f-d9d86c354f31.png)

**Comment by corysimmons** [comment]
Looks like you're exporting
![image](https://user-images.githubusercontent.com/224636/102673053-9a84ea80-4160-11eb-9555-fd32e065bddf.png)

And the dist looks like it's getting bundled:
![image](https://user-images.githubusercontent.com/224636/102673094-bee0c700-4160-11eb-83fc-46504d801591.png)

Is it getting babelified correctly? Not sure it would matter. Even when I test using latest Node (15) locally it gives me the same err.

What am I overlooking? :D

**Comment by jayasurian123** [comment]
hi @corysimmons 
I had updated the docs with the use case 

`const validateFEN = require('fen-validator').default;`

Not sure why it's not getting added in the npm package!!

**Comment by jayasurian123** [comment]
I have updated the patch so the docs would look good in npm also.

**Comment by corysimmons** [comment]
Thank you sir!
