### ISSUE TITLE
Error when submitting non-string arguments to the validation function

### ISSUE THREAD

**Issue by nlukic97** [jayasurian123/fen-validator#22]
If an argument that is not of type 'string' is passed to the **parseFEN** function, this will cause an error when trying to split the **fen** argument.

**Comment by nlukic97** [comment]
I have just created a pull request which should fix this issue: https://github.com/jayasurian123/fen-validator/pull/23

**Comment by jayasurian123** [comment]
good catch. 
If any other type except "string" return false.

**Comment by jayasurian123** [comment]
v1.4.2 has the fix you have submitted. thanks.
