### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by pronode** [jayasurian123/fen-validator#33]
It should be `validateFen.default(...) ` not `validateFen(...)`

**Comment by jayasurian123** [comment]
hi @pronode,
could you tell me the scenario? Is it in the es6 syntax? 

In the commonJs the documentation was written like this.
`const validateFEN = require('fen-validator').default;`

**Comment by pronode** [comment]
Yes, in doc stands:

```
// ES6
import validateFEN from 'fen-validator';

validateFEN('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1'); // true
```

should be:

```
// ES6
import validateFEN from 'fen-validator';

validateFEN.default('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1'); // true
```

just tested with nodeJS

**Comment by nlukic97** [comment]
This is correct. I have tested it as well, and these two options work with nodeJS:

commonjs:
```js
const validateFEN = require('fen-validator').default;

validateFEN('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1'); // true
```

ES6:
```js
import validateFEN from 'fen-validator';

validateFEN.default('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1'); // true
```

**Comment by jayasurian123** [comment]
@nlukic97 I see whats the problem here. This package was written long back. That time there was no native node `import`. babel transpilers would work exactly as mentioned in the docs.
The idea was commonjs is for node and es6 was for browsers (using babel). 

Now the node is implemented `import` (as usual against all the standard), I would create a new major version which would support all the current techs including ts. 👍🏼

**Comment by jayasurian123** [comment]
@nlukic97 Now the new major version is added. 
`cjs, es, iife, umd` supports are added. Now the TS types are also there. 
Now the `default` is no more needed. If possible please verify with the `2.0` version. 🙏🏼

**Comment by nlukic97** [comment]
I've just tested it. It works. ✅

**Comment by jayasurian123** [comment]
@nlukic97  Thank you :)  I will close this issue then 👍🏼

**Comment by jayasurian123** [comment]
@nlukic97  Thank you :)  I will close this issue then 👍🏼
